### ISSUE TITLE
FeatureRequest: record comment sender account info

### ISSUE THREAD

**Issue by Sokwva** [WangHongshuo/AcfunCommentsSplider-go#2]
record the comment sender's acfun account info,such as user id,device model and user name.

**Comment by WangHongshuo** [comment]
i used to record the comment sender's personal info, but this can lead to privacy issues, so i just record the comment.
https://github.com/WangHongshuo/acfun_comments_observer_backend/commit/b8c5af63594cbd7516a1ad8d292f2f0550a9ab6b

**Comment by Sokwva** [comment]
oh sorry,i wasn't thought enough at it out .
