### ISSUE TITLE
how to describe comment floor relation?

### ISSUE THREAD

**Issue by Sokwva** [WangHongshuo/AcfunCommentsSplider-go#3]
how about the comment in a comment?

**Comment by WangHongshuo** [comment]
the observer works in the building mode, not in the the default mode.
in the default mode, we can not realize which comment is deleted.
you can see this, comments are list by floor:
https://github.com/WangHongshuo/acfun_comments_observer_backend/blob/afc1e7c6795f7177aeae09416a806bbc2a2c0c84/commentsob/getter/getter.go#L34

example:
building mode
![image](https://github.com/WangHongshuo/acfun_comments_observer_backend/assets/22424624/90411fee-5644-4618-94fc-1438b9606918)

default mode
![image](https://github.com/WangHongshuo/acfun_comments_observer_backend/assets/22424624/1ccfc70d-5e5e-4bcf-92fe-8352156b1002)

**Comment by WangHongshuo** [comment]
the observer works in the building mode, not the the default mode.
in default mode, we can not realize which comment is deleted.
you can see this, comments are list by floor:
https://github.com/WangHongshuo/acfun_comments_observer_backend/blob/afc1e7c6795f7177aeae09416a806bbc2a2c0c84/commentsob/getter/getter.go#L34

example:
building mode
![image](https://github.com/WangHongshuo/acfun_comments_observer_backend/assets/22424624/90411fee-5644-4618-94fc-1438b9606918)

default mode
![image](https://github.com/WangHongshuo/acfun_comments_observer_backend/assets/22424624/1ccfc70d-5e5e-4bcf-92fe-8352156b1002)

**Comment by Sokwva** [comment]
I mean,just accoding the record from database,we can't reproduce the comment relation.for example,comment A is the reply of comment B but when fetch record from database we cant find which comment is 'a sub-comment in comment floor'.

**Comment by WangHongshuo** [comment]
we know.
this project doesn't focus on the relation between comments. we just focus on the comment which is deleted by user, admin or system. (that means we hope to save the comment before it is deleted.)
but u can check out the json file we used for testing:
https://github.com/WangHongshuo/acfun_comments_observer_backend/blob/afc1e7c6795f7177aeae09416a806bbc2a2c0c84/commentsob/getter/comments.json#L120
the quoteId is the relation between comments in the building mode, but we didn't save it.
as for the default mode,  the rootComments and subCommentsMap can describe the relation between comments.
![image](https://github.com/WangHongshuo/acfun_comments_observer_backend/assets/22424624/0dbb791a-3cdd-46e8-bdf4-dae67e65a342)

technically, it's not difficult to restore the relationship between all the comments, but that is not our goal.

**Comment by Sokwva** [comment]
thanks.
